# Generated by Django 3.2.12 on 2023-06-05 19:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='customer_tmaskpl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=100)),
                ('customer_skrot_firmy', models.CharField(max_length=50, null=True, verbose_name='Skrót firmy')),
                ('customer_miasto', models.CharField(blank=True, max_length=50, null=True, verbose_name='Miasto')),
                ('customer_kod_pocztowy', models.CharField(blank=True, max_length=6, null=True, verbose_name='Kod pocztowy')),
                ('customer_ul', models.CharField(blank=True, max_length=50, null=True, verbose_name='Nazwa ulicy')),
                ('customer_nr_lok', models.CharField(blank=True, max_length=50, null=True, verbose_name='Numer lokalu')),
                ('customer_telefon', models.CharField(max_length=50, null=True, validators=[django.core.validators.RegexValidator('^[0-9]+', 'Only digit characters.')], verbose_name='Telefon')),
                ('customer_email', models.EmailField(max_length=50, null=True, verbose_name='Email')),
                ('customer_github', models.CharField(blank=True, max_length=250, null=True, verbose_name='Github')),
                ('customer_facebook', models.CharField(blank=True, max_length=250, null=True, verbose_name='Facebook')),
                ('customer_linkedin', models.CharField(blank=True, max_length=250, null=True, verbose_name='LinkedIn')),
                ('customer_opis', models.TextField(blank=True, default='', verbose_name='Opis')),
                ('customer_data_wprowadzenia', models.DateTimeField(auto_now_add=True, verbose_name='Data utworzenia')),
                ('customer_data_aktualizacji', models.DateTimeField(auto_now=True, null=True, verbose_name='Data ostatniej aktualizacji')),
                ('customer_upload', models.FileField(upload_to='uploads/% Y/% m/% d/')),
            ],
            options={
                'verbose_name': 'Customer',
                'verbose_name_plural': 'Customer',
            },
        ),
    ]
