# Generated by Django 3.2.12 on 2023-06-02 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ansible_tmaskpl_app', 'old_0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer_tmaskpl',
            options={'verbose_name': 'Customer', 'verbose_name_plural': 'Customer'},
        ),
        migrations.AddField(
            model_name='customer_tmaskpl',
            name='customer_data_aktualizacji',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created Time'),
        ),
        migrations.AddField(
            model_name='customer_tmaskpl',
            name='customer_data_wprowadzenia',
            field=models.DateTimeField(null=True, verbose_name='Data utworzenia'),
        ),
        migrations.AddField(
            model_name='customer_tmaskpl',
            name='customer_kod_pocztowy',
            field=models.CharField(max_length=6, null=True, verbose_name='Kod pocztowy'),
        ),
        migrations.AddField(
            model_name='customer_tmaskpl',
            name='customer_miasto',
            field=models.CharField(max_length=50, null=True, verbose_name='Miasto'),
        ),
        migrations.AddField(
            model_name='customer_tmaskpl',
            name='customer_nr_lok',
            field=models.CharField(max_length=50, null=True, verbose_name='Numer lokalu'),
        ),
        migrations.AddField(
            model_name='customer_tmaskpl',
            name='customer_opis',
            field=models.TextField(default='', null=True, verbose_name='Opis'),
        ),
        migrations.AddField(
            model_name='customer_tmaskpl',
            name='customer_skrot_firmy',
            field=models.CharField(max_length=50, null=True, verbose_name='Skrót firmy'),
        ),
        migrations.AddField(
            model_name='customer_tmaskpl',
            name='customer_ul',
            field=models.CharField(max_length=50, null=True, verbose_name='Nazwa ulicy'),
        ),
    ]
