# Generated by Django 3.2.12 on 2023-06-05 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ansible_tmaskpl_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer_tmaskpl',
            name='customer_upload',
            field=models.FileField(blank=True, null=True, upload_to='uploads/% Y/% m/% d/'),
        ),
    ]
