# Generated by Django 3.2.12 on 2023-06-06 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ansible_tmaskpl_app', '0002_alter_customer_tmaskpl_customer_upload'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer_tmaskpl',
            options={'verbose_name': 'Customer TMaskPL', 'verbose_name_plural': 'Customer'},
        ),
        migrations.AlterField(
            model_name='customer_tmaskpl',
            name='customer_name',
            field=models.CharField(max_length=100, verbose_name='Pełna nazwa firmy'),
        ),
        migrations.AlterField(
            model_name='customer_tmaskpl',
            name='customer_upload',
            field=models.FileField(blank=True, null=True, upload_to='%Y/%m/%d/'),
        ),
    ]
